version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypass
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
